import React from "react";
import Head from "next/head";
import Nav from "../pages/components/nav";
import Cards from "../pages/components/cards";


export default function menu(){
    return(
        <>
            <Head>
                <title>Menu Principal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logoCoopIcono.ico" />
            </Head>
            <div className="conteiner">
                <Nav />
                <div className="cardsGerenal">
                  <Cards />
                  <Cards />
                  <Cards />
                </div>
            </div>
        </>
    );
};
