import React from "react";
import { useState } from "react";
import Head from "next/head";
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import Col from 'react-bootstrap/Col';
import Form from 'react-bootstrap/Form';
import Row from 'react-bootstrap/Row';
import SearchIcon from '@mui/icons-material/Search';
import Table from 'react-bootstrap/Table';
import Nav from '../pages/components/nav';

const note = [
  {
    user:"Claudio Peschiutta",
    equipo:"Notebook Tel-PC",
    area:"Telefonia",
    marca:"Lenovo",
    tipo:"I3 - 4 Ram - 500 Ssd",
    vpn:null,
    serie:""
  },
  {
    user:"Exequiel Isasmendi",
    equipo:"Ezequiel Isasmendi",
    area:"Personal",
    marca:"Bangho",
    tipo:"I7G10 - 16 Ram - 500 Ssd",
    vpn:"notebookRRHH",
    serie:""
  },
  {
    user:"Gabriel Frizza",
    equipo:"Gabriel-Frizza",
    area:"Internet",
    marca:"Lenovo ThinPad",
    tipo:"I11G7 - 16 Ram - 500 Ssd",
    vpn:"gfrizza",
    serie:""
  },
  {
    user:"Gerardo Rui",
    equipo:"SISTEMASNOTE5",
    area:"Sistemas",
    marca:"Bangho",
    tipo:"I7G4 - 8 Ram - 240 Ssd",
    vpn:"CVPN5",
    serie:"09000451601001191"
  },
  {
    user:"Laura Oliver",
    equipo:"Laura Oliver",
    area:"Gerencia",
    marca:"Dell",
    tipo:"I5G11 - 8 Ram - 500 Ssd",
    vpn:"loliver",
    serie:""
  },
  {
    user:"Luis Peschiutta",
    equipo:"Alan Ledesma",
    area:"Tecnica",
    marca:"Lenovo Thinkbook",
    tipo:"I5 - 16 Ram - 500 Ssd",
    vpn:"NotebookOffTecnica3",
    serie:"C-22785"
  },
  {
    user:"Marcos Berrondo",
    equipo:"Desktop-gtog2sl",
    area:"Tecnica",
    marca:"Lenovo",
    tipo:"I7 - 8 Ram  - 240 Ssd",
    vpn:"mberrondoNote",
    serie:""
  },
  {
    user:"Mario Arlla",
    equipo:"SISTEMASNOTE6",
    area:"Redes",
    marca:"Toshiba",
    tipo:"I3G3 - 4 Ram - 240 Ssd",
    vpn:"NtbkToshiba",
    serie:""
  },
  {
    user:"Maximiliano Aguero",
    equipo:"SISTEMANOTE4",
    area:"Contaduria",
    marca:"Bangho",
    tipo:"I7G7 - 8 Ram - 1TB",
    vpn:"CVPN7",
    serie:""
  },
  {
    user:"Mercedes Seculini",
    equipo:"SISTEMASNOTE3",
    area:"Personal",
    marca:"CX Infinito",
    tipo:"I5G3 - 8 Ram - 240 Ssd",
    vpn:"CVPNcxtest",
    serie:"0010PX000400594248"
  },
  {
    user:"Raul Toledo",
    equipo:"GERENCIA",
    area:"Gerencia",
    marca:"Dell",
    tipo:"I5G11 - 8 Ram - 240 Ssd",
    vpn:"rtoledo",
    serie:"ST:GTV3JQ3"
  },
  {
    user:"Rodrigo Guzman",
    equipo:"REDES-NOTE",
    area:"Redes",
    marca:"CX Infinito",
    tipo:"I5G3 - 8 Ram - 240 Ssd",
    vpn:"redes-note",
    serie:""
  },
  {
    user:"Secretaria",
    equipo:"SECRETARIA-NOTE",
    area:"Secretaria",
    marca:"Lenovo",
    tipo:"I3G4 - 4 Ram - 240 Ssd",
    vpn:"C.Maldonado",
    serie:"PE9016505001"
  },
  {
    user:"Sistemas",
    equipo:"SistemasNote6",
    area:"Sistemas",
    marca:"Samsung",
    model:"",
    tipo:"Quad-Core - 4 Ram -240 Ssd",
    vpn:"sistemasNote6",
    serie:"NP915S3G-K03AR"
  },
  {
    user:"Sistemas",
    equipo:"Notebook-Samsung",
    area:"Sistemas",
    marca:"Samsung",
    tipo:"I5G3 - 6 Ram - 1TB",
    vpn:"NotebookSamsung01",
    serie:""
  },
  {
    user:"Sistemas",
    equipo:"SISTEMACOOP",
    area:"Sistemas",
    marca:"Bangho",
    tipo:"I5G7 - 8 Ram - 240 Ssd",
    vpn:"sistemaCoop",
    serie:""
  },
  {
    user:"",
    equipo:"",
    area:"",
    marca:"",
    tipo:"",
    vpn:"",
    serie:""
  },
  
]

export default function notebook (){

  const [user, setUser] = useState('');
  const [area, setArea] = useState('');
  const [datosFiltrados, setDatosFiltrados] = useState([]);

  const handleFiltrar = () => {
    const datosFiltrados = note.filter((item) =>{
      return (
        (user === '' || item.user === user) &&
        (area === '' || item.area === area) 
      );
    });
  
    setDatosFiltrados(datosFiltrados);
  };

   //Modal abrir y cerrar
 const [show, setShow] = useState(false);

 const handleClose = () => setShow(false);
 const handleShow = () => setShow(true);
  
    return(
        <>
          <Head>
            <title>Notebook</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logoCoopIcono.ico" />
          </Head>
          <Nav /> 
            <div className="conteinerNotebook">
              <h1>Notebook</h1>
              <Form className="formNotebook">
                <Row className="mb-3">
                <Form.Group as={Col} controlId="formGridState">
                    <Form.Label><b>Usuario</b></Form.Label>
                    <Form.Select value={user} onChange={(e)=>setUser(e.target.value)}>
                      <option></option>
                      <option>Claudio Peschiutta</option>
                      <option>Exequiel Isasmendi</option>
                      <option>Gabriel Frizza</option>
                      <option>Gerardo Rui</option>
                      <option>Laura Oliver</option>
                      <option>Luis Peschiutta</option>
                      <option>Marcos Berrondo</option>
                      <option>Mario Arlla</option>
                      <option>Maximiliano Agüero </option>
                      <option>Mercedes Seculini</option>
                      <option>Raúl Toledo</option>
                      <option>Rodrigo Guzmán </option>
                      <option>Secretaria</option>
                      <option>Sistemas</option>
                    </Form.Select>
                  </Form.Group>

                  <Form.Group as={Col} controlId="formGridState">
                    <Form.Label><b>Area</b></Form.Label>
                    <Form.Select value={area} onChange={(e)=>setArea(e.target.value)}>
                      <option></option>
                      <option value="Contaduría">Contaduría</option>
                      <option value="Gerencia">Gerencia</option>
                      <option value="Internet">Internet</option>
                      <option value="Mantenimiento">Mantenimiento</option>
                      <option value="Personal">Personal</option>
                      <option value="Redes Eléctricas">Redes Eléctricas</option>
                      <option value="Secretaria">Secretaria</option>
                      <option value="Sistemas">Sistemas</option>
                      <option value="Técnica">Técnica</option>
                      <option value="Telefonía">Telefonía</option>
                      <option value="Tesorería">Tesorería</option>
                    </Form.Select>
                  </Form.Group>
                </Row>

                <Button variant="secondary" onClick={handleFiltrar}><SearchIcon />
                  Buscar
                </Button>
              </Form>

              <div className="tablaDataNotebook">
                <Table striped bordered hover size="sm" >
                  <thead>
                    <tr>
                      <th>Usuario</th>
                      <th>Area</th>
                      <th>Más Informacion</th>
                    </tr>
                  </thead>
                  <tbody>
                    {datosFiltrados.map((item,index)=>(
                      <tr key={index}>
                      <td>{item.user}</td>
                      <td>{item.area}</td>
                      <td>
                        <Button variant="info" onClick={handleShow}>Ver Más</Button>
                      </td>
                    </tr>
                    ))}
      
                  </tbody>
                </Table>
              </div>

              {/*Modal Info Notebook*/}
              <Modal show={show} onHide={handleClose} centered>
                <Modal.Header closeButton>
                  <Modal.Title>Notebook de Cooperativa CC y JM</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                  <p>Notebook</p>
                  <p>Sistemas</p>
                  <p>Core I5 - 4 Ram - 240 Ssd</p>
                </Modal.Body>
                <Modal.Footer>
                  <Button variant="primary" onClick={handleClose}>
                    Save Changes
                  </Button>
                </Modal.Footer>
              </Modal>

            </div>
        </>
    )
}